### ISSUE TITLE
Remove inline styles

### ISSUE THREAD

**Issue by natec425** [HenryMoore13/HenryMoore_Web_Rental_Agency#3]
These could be moved into your own css or replaced with a bootstrap class. Appropriate use of Bootstrap's grid system ([docs](https://getbootstrap.com/docs/4.1/layout/grid/)) should solve this.

https://github.com/HenryMoore13/HenryMoore_Web_Rental_Agency/blob/236c0df0a6ece4e871cb495c2a5198bd6e7724d9/index.html#L21

https://github.com/HenryMoore13/HenryMoore_Web_Rental_Agency/blob/236c0df0a6ece4e871cb495c2a5198bd6e7724d9/index.html#L35

https://github.com/HenryMoore13/HenryMoore_Web_Rental_Agency/blob/236c0df0a6ece4e871cb495c2a5198bd6e7724d9/index.html#L42

https://github.com/HenryMoore13/HenryMoore_Web_Rental_Agency/blob/236c0df0a6ece4e871cb495c2a5198bd6e7724d9/index.html#L51

https://github.com/HenryMoore13/HenryMoore_Web_Rental_Agency/blob/236c0df0a6ece4e871cb495c2a5198bd6e7724d9/index.html#L60

https://github.com/HenryMoore13/HenryMoore_Web_Rental_Agency/blob/236c0df0a6ece4e871cb495c2a5198bd6e7724d9/index.html#L67

https://github.com/HenryMoore13/HenryMoore_Web_Rental_Agency/blob/236c0df0a6ece4e871cb495c2a5198bd6e7724d9/index.html#L77

https://github.com/HenryMoore13/HenryMoore_Web_Rental_Agency/blob/236c0df0a6ece4e871cb495c2a5198bd6e7724d9/index.html#L86

https://github.com/HenryMoore13/HenryMoore_Web_Rental_Agency/blob/236c0df0a6ece4e871cb495c2a5198bd6e7724d9/index.html#L95

https://github.com/HenryMoore13/HenryMoore_Web_Rental_Agency/blob/236c0df0a6ece4e871cb495c2a5198bd6e7724d9/index.html#L102

**Comment by HenryMoore13** [comment]
Hey just added a commit for this. Does this look good?

**Comment by natec425** [comment]
:+1:  LGTM
